# 1. NumPy入門（Pythonでの数値計算ライブラリの基本）

In [65]:
# ライブラリの読み込み
import numpy as np

# PythonのリストからNumPyの多次元配列（ndarray）を生成
arr = np.array([1, 2, 3, 4, 5])

# 配列の内容を表示
print(arr)

# 配列の型情報を確認
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 2.numpyの属性

In [66]:
# ① 3行5列のNumPy配列（ndarray）を生成
arr = np.arange(15).reshape((3, 5))  
# np.arange(15)はPythonのrange(15)と同様に0〜14の連続データを生成し、
# reshape((3, 5))によって3行5列の2次元配列に変換する

print(f'ndarrayオブジェクト: {arr}')  # ndarrayの内容を出力

# 配列の形状（各次元の要素数）を取得
print(f'配列の形状（shape）: {arr.shape}')  # (3, 5) → 3行5列

# 配列の次元数（軸の数）を取得
print(f'配列の次元数（ndim）: {arr.ndim}')  # 2 → 2次元配列

# 配列内の全要素数を取得
print(f'配列の要素数（size）: {arr.size}')  # 15

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr.dtype}')  # int64

# 1要素あたりのメモリ使用量（バイト数）
print(f'1要素あたりのサイズ（itemsize）: {arr.itemsize}')  # 8バイト

# オブジェクトの型情報を確認
print(f'配列の型: {type(arr)}')  # <class 'numpy.ndarray'>

ndarrayオブジェクト: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
配列の形状（shape）: (3, 5)
配列の次元数（ndim）: 2
配列の要素数（size）: 15
要素のデータ型（dtype）: int32
1要素あたりのサイズ（itemsize）: 4
配列の型: <class 'numpy.ndarray'>


In [67]:
# 補足: 上記のshapeやndim、sizeなどの属性は、
# 「np.関数名(配列オブジェクト)」という形式でも取得可能

print(f'配列の形状（shape）: {np.shape(arr)}')  # (3, 5) → 3行5列
print(f'配列の次元数（ndim）: {np.ndim(arr)}')  # 2 → 2次元配列
print(f'配列の要素数（size）: {np.size(arr)}')  # 15

# 以下のような関数はNumPyには存在しないためエラーになる
# print(f'要素のデータ型: {np.dtype(arr)}')      # エラー（この形式の関数は存在しない）
# print(f'要素のサイズ: {np.itemsize(arr)}')    # エラー（同上）
# print(f'配列の型: {np.type(arr)}')            # エラー（同上）

配列の形状（shape）: (3, 5)
配列の次元数（ndim）: 2
配列の要素数（size）: 15


# 3. ndarrayオブジェクトの作成（NumPy配列の生成）

## 3.1 Pythonのリストをndarrayオブジェクト（NumPy配列）に変換する

In [68]:
# 整数型（int）のNumPy配列を生成
arr1 = np.array([1, 2, 3, 4, 5])

# 配列の内容を出力
print(f'配列オブジェクト: {arr1}')

# 配列オブジェクト自体の型を確認
print(f'配列の型: {type(arr1)}')

# 配列内の要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr1.dtype}')

配列オブジェクト: [1 2 3 4 5]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: int32


In [69]:
# 浮動小数点数（float）のNumPy配列を生成
arr2 = np.array([1.2, 2.3, 3.4])

# 配列の内容を出力
print(f'配列オブジェクト: {arr2}')

# 配列オブジェクト自体の型を確認
print(f'配列の型: {type(arr2)}')

# 配列内の要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr2.dtype}')

配列オブジェクト: [1.2 2.3 3.4]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: float64


## 3.2 zeros() / ones() / empty() 関数を使ってndarrayオブジェクトを作成する

In [70]:
# zeros() 创建全是0的数组, 即: ndarray对象
arr3 = np.zeros((2, 3))  # 2行3列, 即: 二维数组, 有2个一维数组, 每个一维数组的元素个数为: 3
print(f'数组对象: {arr3}')  # [[0. 0. 0.]  [0. 0. 0.]]
print(f'数组类型: {type(arr3)}')  # <class 'numpy.ndarray'>
print(f'数组元素类型: {arr3.dtype}')  # float64

数组对象: [[0. 0. 0.]
 [0. 0. 0.]]
数组类型: <class 'numpy.ndarray'>
数组元素类型: float64


In [71]:
# zeros関数を使用して、すべての要素が0のNumPy配列（ndarray）を生成
arr3 = np.zeros((2, 3))  
# (2, 3)は配列の形状を表し、2行3列の2次元配列を意味する
# つまり、要素数3の1次元配列が2つ含まれる構造

# 配列の内容を出力
print(f'配列オブジェクト: {arr3}')  # [[0. 0. 0.]  [0. 0. 0.]]

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr3)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr3.dtype}')  # float64

配列オブジェクト: [[0. 0. 0.]
 [0. 0. 0.]]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: float64


In [72]:
# empty関数を使用して、未初期化のNumPy配列（ndarray）を生成
arr5 = np.empty((2, 3))  
# (2, 3)は配列の形状を表し、2行3列の2次元配列を意味する
# emptyはメモリを確保するのみで初期化を行わないため、値は不定（環境やメモリ状態に依存）

# 配列の内容を出力
print(f'配列オブジェクト: {arr5}')  
# ※ 出力結果はランダムではなく「未定義の値」（以前のメモリ内容が残る場合がある）

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr5)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr5.dtype}')  # float64

配列オブジェクト: [[0.28137814 0.04144687 0.06542302]
 [0.03586011 0.64275388 0.60361098]]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: float64


## 3.3 arange()関数を使ってndarrayオブジェクトを作成する（等差数列の配列生成）

In [73]:
# arange関数を使用して、一定間隔の数値列を生成（Pythonのrangeに類似）
arr6 = np.arange(1, 5, 2, dtype=np.float32)  
# 開始値=1、終了値=5（終了値は含まれない）、ステップ=2
# dtypeを指定することで、要素のデータ型を明示的に設定可能（例：int32, int64, float32, float64 など）

# 配列の内容を出力
print(f'配列オブジェクト: {arr6}')

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr6)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr6.dtype}')  # float32

配列オブジェクト: [1. 3.]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: float32


## 3.4 matrix() を使って2次元配列（行列）を生成する

In [74]:
# matrixクラスを使用して2次元配列を生成（※現在は非推奨に近い扱い）
# arr7 = np.mat('1 2; 3 4')
# arr7 = np.mat('1,2;3,4')
# arr7 = np.mat([[1, 2, 3], [4, 5, 6]])

arr7 = np.matrix([[1, 2, 3], [4, 5, 6]])  
# matrixは常に2次元配列を扱うためのクラス

# 配列の内容を出力
print(f'配列オブジェクト: {arr7}')

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr7)}')  
# <class 'numpy.matrix'>（ndarrayのサブクラス）

# 配列要素のデータ型を確認

配列オブジェクト: [[1 2 3]
 [4 5 6]]
配列の型: <class 'numpy.matrix'>


## 3.5 rand() / randint() / uniform() を使ってndarrayオブジェクトを生成する（乱数配列の作成）

In [75]:
# rand関数を使用して、0.0以上1.0未満の一様分布に従う乱数配列を生成
arr8 = np.random.rand(2, 3)  
# (2, 3)は配列の形状を表し、2行3列の2次元配列を生成

# 配列の内容を出力
print(f'配列オブジェクト: {arr8}')  
# ※ 各要素は0.0以上1.0未満のランダムな浮動小数点数

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr8)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr8.dtype}')  # float64

配列オブジェクト: [[0.1772889  0.74818531 0.23342391]
 [0.83738998 0.76490214 0.20358781]]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: float64


In [76]:
# randint関数を使用して、指定範囲の整数乱数配列を生成
arr9 = np.random.randint(-1, 5, size=(2, 3))  
# -1以上5未満の範囲からランダムな整数を生成（終了値は含まれない）
# size=(2, 3) → 2行3列の2次元配列

# 配列の内容を出力
print(f'配列オブジェクト: {arr9}')  
# ※ 各要素は指定範囲内のランダムな整数

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr9)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr9.dtype}')  # int64

配列オブジェクト: [[2 0 4]
 [2 2 4]]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: int32


In [77]:
# uniform関数を使用して、指定範囲の一様分布に従う乱数配列を生成
arr10 = np.random.uniform(-1, 5, size=(2, 3))  
# -1以上5未満の範囲でランダムな浮動小数点数を生成
# size=(2, 3) → 2行3列の2次元配列

# 配列の内容を出力
print(f'配列オブジェクト: {arr10}')  
# ※ 各要素は指定範囲内のランダムな浮動小数点数

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr10)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr10.dtype}')  # float64

配列オブジェクト: [[ 4.49089129 -0.10503621  3.04435076]
 [ 4.60980001 -0.86590715  2.24698346]]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: float64


## 3.6 astype()関数を使って、ndarrayのデータ型を変換する（ndarray → ndarray）

In [78]:
# ones関数を使用して、すべての要素が1の浮動小数点配列を生成
arr11 = np.ones((2, 3), dtype=np.float32)  
# (2, 3) → 2行3列の2次元配列
# dtypeを指定することで、要素のデータ型をfloat32に設定

# 配列の内容を出力
print(f'配列オブジェクト: {arr11}')  
# [[1. 1. 1.]
#  [1. 1. 1.]]

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr11)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr11.dtype}')  # float32

配列オブジェクト: [[1. 1. 1.]
 [1. 1. 1.]]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: float32


In [79]:
# astypeメソッドを使用して、配列のデータ型をfloat32からint64に変換
arr12 = arr11.astype(np.int64)

# 配列の内容を出力
print(f'配列オブジェクト: {arr12}')  
# [[1 1 1]
#  [1 1 1]]

# 配列オブジェクトの型を確認
print(f'配列の型: {type(arr12)}')  # <class 'numpy.ndarray'>

# 配列要素のデータ型を確認
print(f'要素のデータ型（dtype）: {arr12.dtype}')  # int64

配列オブジェクト: [[1 1 1]
 [1 1 1]]
配列の型: <class 'numpy.ndarray'>
要素のデータ型（dtype）: int64


## 3.7 logspace()（等比数列）と linspace()（等差数列）を使ったndarrayの生成

In [80]:
# logspace(開始の指数, 終了の指数, 要素数, base=底)  
# base^開始指数 ～ base^終了指数 の範囲で、指定した要素数のデータを生成（等比数列）
# 底はデフォルトで10、任意の値に変更可能
# arr13 = np.logspace(0, 5, 10)         # 10^0 ～ 10^5 の範囲、要素数10、等比数列
arr13 = np.logspace(0, 5, 10, base=2)  # 2^0 ～ 2^5 の範囲、要素数10、等比数列

print(f'配列オブジェクト: {arr13}')      # [[1 1 1] [1 1 1]]
print(f'配列の型: {type(arr13)}')       # <class 'numpy.ndarray'>
print(f'配列の要素型: {arr13.dtype}')   # int64

配列オブジェクト: [ 1.          1.46973449  2.16011948  3.1748021   4.66611616  6.85795186
 10.0793684  14.8139954  21.77264    32.        ]
配列の型: <class 'numpy.ndarray'>
配列の要素型: float64


In [81]:
# linspace(開始値, 終了値, 要素数, endpoint=True|False)  
# 開始値 ～ 終了値の範囲で、指定した要素数のデータを生成（等差数列）
# endpoint=True（デフォルト）の場合は終了値を含む、Falseの場合は終了値を含まない
arr14 = np.linspace(0, 5, 5)  # 0 ～ 5 の範囲、要素数5、等差数列（endpoint=True：終了値を含む）
arr14 = np.linspace(0, 5, 5, endpoint=False)  # 0 ～ 5 の範囲、要素数5、等差数列（左閉右開：終了値を含まない）

print(f'配列オブジェクト: {arr14}')      # [[1 1 1] [1 1 1]]
print(f'配列の型: {type(arr14)}')       # <class 'numpy.ndarray'>
print(f'配列の要素型: {arr14.dtype}')   # int64

配列オブジェクト: [0. 1. 2. 3. 4.]
配列の型: <class 'numpy.ndarray'>
配列の要素型: float64


# 4. NumPyの組み込み関数（便利な関数群）

## 4.1 組み込み関数：基本関数（ベーシック関数）

In [82]:
# 基本関数は以下の通り：
# ceil(), floor(), rint(), isnan(), abs(), multiply(), divide(), where()

# np.ceil(): 切り上げ（最も近い上の整数へ）、引数は number または array
# np.floor(): 切り捨て（最も近い下の整数へ）、引数は number または array
# np.rint(): 四捨五入、引数は number または array
# np.isnan(): 要素が NaN（Not a Number）かどうかを判定、引数は number または array
# np.multiply(): 要素同士の乗算、引数は number または array
# np.divide(): 要素同士の除算、引数は number または array
# np.abs(): 要素の絶対値、引数は number または array
# np.where(condition, x, y): 三項演算子、condition が True のとき x、そうでなければ y

# 注意：multiply / divide で2つの ndarray を演算する場合、shape（形状）が一致している必要がある

# 1. ndarrayオブジェクトの生成
arr = np.random.randn(2, 3)  # 標準正規分布に従う 2行3列のデータを生成
print(f'arrの値: {arr}')    

# 2. 各関数のデモ
print(np.ceil(arr))              # 切り上げ
print(np.floor(arr))             # 切り捨て
print(np.rint(arr))              # 四捨五入
print(np.isnan(arr))             # NaN判定
print(np.abs(arr))               # 絶対値
print(np.multiply(arr, arr))     # 要素ごとの積
print(np.divide(arr, arr))       # 要素ごとの商
print(np.where(arr > 0, 1, -1))  # 条件分岐（正なら1、負なら-1）

arrの値: [[-0.55347343  0.50664237 -0.01151393]
 [-0.18125369  1.78851302  0.97835493]]
[[-0.  1. -0.]
 [-0.  2.  1.]]
[[-1.  0. -1.]
 [-1.  1.  0.]]
[[-1.  1. -0.]
 [-0.  2.  1.]]
[[False False False]
 [False False False]]
[[0.55347343 0.50664237 0.01151393]
 [0.18125369 1.78851302 0.97835493]]
[[3.06332836e-01 2.56686494e-01 1.32570675e-04]
 [3.28529017e-02 3.19877884e+00 9.57178366e-01]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1  1 -1]
 [-1  1  1]]


## 4.2 組み込み関数：統計関数（集計・統計処理）

In [83]:
# 統計関数の説明
# np.mean(), np.sum()：全要素の平均値、全要素の合計（引数は number または array）
# np.max(), np.min()：全要素の最大値、全要素の最小値（引数は number または array）
# np.std(), np.var()：全要素の標準偏差、全要素の分散（引数は number または array）
# np.argmax(), np.argmin()：最大値・最小値のインデックス（位置）を返す（引数は number または array）
# np.cumsum(), np.cumprod()：1次元配列を返し、それぞれ累積和・累積積を計算（引数は number または array）
# 多次元配列ではデフォルトで全体を対象に計算する。
# axisパラメータで軸を指定可能：axis=0 は列方向、axis=1 は行方向

# 1. ndarrayオブジェクトの生成
arr = np.arange(12).reshape((3, 4))  # 3行4列の配列
print(f'要素内容: {arr}')

# 2. cumsum()（累積和）の例
print(np.cumsum(arr))  # [ 0  1  3  6 10 15 21 28 36 45 55 66]

# 3. sum()（合計）の例
print(np.sum(arr))          # 全要素の合計 → 66
print(np.sum(arr, axis=0))  # 列ごとの合計 → [12, 15, 18, 21]
print(np.sum(arr, axis=1))  # 行ごとの合計 → [6, 22, 38]

要素内容: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  3  6 10 15 21 28 36 45 55 66]
66
[12 15 18 21]
[ 6 22 38]


# 4.3 組み込み関数：比較関数（比較・判定系関数）

In [84]:
# any()：いずれか1つの要素が条件を満たせば True、そうでなければ False
# all()：すべての要素が条件を満たす場合のみ True、そうでなければ False

# 1. 配列を生成
arr = np.random.randn(2, 3)  # 2行3列の標準正規分布データ
print(arr)

# 2. 比較関数の例
print(np.any(arr > 0))  # 配列内のいずれかの要素が0より大きければ True
print(np.all(arr > 0))  # 配列内のすべての要素が0より大きければ True

[[ 0.55823072  1.26445488 -0.71724864]
 [ 0.01477479 -0.49690199  0.33443304]]
True
False


## 4.4 組み込み関数：ソート関数（並び替え処理）

In [85]:
# 方法1: np.sort(arr)     ソートして新しい配列（コピー）を返す
# 方法2: arr.sort()       元の配列を直接ソートする（インプレース処理）

# 1. ndarrayオブジェクトの生成
arr = np.array([1, 5, 3, 2, 6])
print(f'ソート前: {arr}')

# 2. ソート
# arr_copy = np.sort(arr)
# print(f'np.sort()の結果: {arr_copy}')

arr.sort()  # 元の配列を直接ソート

# 3. ソート後
print(f'ソート後: {arr}')

ソート前: [1 5 3 2 6]
ソート後: [1 2 3 5 6]


## 4.5 組み込み関数：重複除去関数（ユニーク処理）

In [86]:
# unique(): 重複要素を削除する関数（Pythonの set() に類似）

# 1. ndarrayオブジェクトの生成
arr = np.array([[1, 2, 1, 6], [1, 3, 2, 5]])  # 注意：各行の列数は一致している必要がある
print(f'重複削除前: {arr}')

# 2. 重複削除
new_arr = np.unique(arr)

# 3. 結果を出力
print(f'重複削除後: {new_arr}')

重複削除前: [[1 2 1 6]
 [1 3 2 5]]
重複削除後: [1 2 3 5 6]


# 5. NumPyの演算（配列計算・数値演算）

## 5.1 基本演算（対応する要素同士でそのまま計算する）

In [87]:
# 1. 2つのndarrayオブジェクトを作成
arr1 = np.array([10, 20, 30, 40])       # [10, 20, 30, 40]
arr2 = np.arange(4)                     # [0, 1, 2, 3]

# 2. 基本演算（要素ごとの計算）
arr3 = arr1 + arr2
arr4 = arr1 * arr2
arr5 = np.multiply(arr1, arr2)

# 3. 結果を出力
print(f'arr1: {arr1}')   # [10, 20, 30, 40]
print(f'arr2: {arr2}')   # [0, 1, 2, 3]
print(f'arr3: {arr3}')   # [10, 21, 32, 43]
print(f'arr4: {arr4}')   # [0, 20, 60, 120]
print(f'arr5: {arr5}')   # [0, 20, 60, 120]

arr1: [10 20 30 40]
arr2: [0 1 2 3]
arr3: [10 21 32 43]
arr4: [  0  20  60 120]
arr5: [  0  20  60 120]


## 5.2 行列演算（行列の次元が一致する場合）

In [88]:
# 1. 2次元ndarrayオブジェクトを作成（行列演算のデモ用）
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # [[1, 2, 3], [4, 5, 6]]
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # [[1, 2, 3], [4, 5, 6]]

# 2. 基本演算（要素ごとの乗算）
arr3 = arr1 * arr2
arr4 = np.multiply(arr1, arr2)

# 3. 結果を出力
print(f'arr1: {arr1}')   # [[1, 2, 3], [4, 5, 6]]
print(f'arr2: {arr2}')   # [[1, 2, 3], [4, 5, 6]]
print(f'arr3: {arr3}')   # [[1, 4, 9], [16, 25, 36]]
print(f'arr4: {arr4}')   # [[1, 4, 9], [16, 25, 36]]

arr1: [[1 2 3]
 [4 5 6]]
arr2: [[1 2 3]
 [4 5 6]]
arr3: [[ 1  4  9]
 [16 25 36]]
arr4: [[ 1  4  9]
 [16 25 36]]


## 5.3 行列演算（行列の次元が逆の場合：転置や行列積の例）

In [89]:
# dot()関数：行列の次元が逆の場合に使用（行列積）
# 1. 2次元ndarrayオブジェクトを作成（行列演算デモ用）
arr1 = np.array([[1, 2, 3], [4, 5, 6]])       # [[1, 2, 3], [4, 5, 6]]
arr2 = np.array([[9, 8], [6, 5], [3, 2]])     # [[9, 8], [6, 5], [3, 2]]

# 2. 行列積の計算
arr3 = arr1.dot(arr2)

# 3. 結果を出力
print(f'arr3: {arr3}')  # [[30 24] [84 69]]

arr3: [[30 24]
 [84 69]]
